// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsVideoFiltersApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsVideoFiltersApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsVideoFiltersApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashVideoFiltersApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashVideoFiltersApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashVideoFiltersApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct VideoFilterConfig: Hashable {
  var exposure: Double
  var contrast: Double
  var saturation: Double
  var temperature: Double
  var tint: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoFilterConfig? {
    let exposure = pigeonVar_list[0] as! Double
    let contrast = pigeonVar_list[1] as! Double
    let saturation = pigeonVar_list[2] as! Double
    let temperature = pigeonVar_list[3] as! Double
    let tint = pigeonVar_list[4] as! Double

    return VideoFilterConfig(
      exposure: exposure,
      contrast: contrast,
      saturation: saturation,
      temperature: temperature,
      tint: tint
    )
  }
  func toList() -> [Any?] {
    return [
      exposure,
      contrast,
      saturation,
      temperature,
      tint,
    ]
  }
  static func == (lhs: VideoFilterConfig, rhs: VideoFilterConfig) -> Bool {
    return deepEqualsVideoFiltersApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashVideoFiltersApi(value: toList(), hasher: &hasher)
  }
}

private class VideoFiltersApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return VideoFilterConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VideoFiltersApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VideoFilterConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VideoFiltersApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VideoFiltersApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VideoFiltersApiPigeonCodecWriter(data: data)
  }
}

class VideoFiltersApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VideoFiltersApiPigeonCodec(readerWriter: VideoFiltersApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VideoFiltersApi {
  func loadVideo(path: String) throws
  func play() throws
  func pause() throws
  func getVideoDuration() throws -> Double
  func getVideoPosition() throws -> Double
  func updateFilters(config: VideoFilterConfig) throws
  func setLutCubePath(path: String) throws
  func setHaldPngPath(path: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VideoFiltersApiSetup {
  static var codec: FlutterStandardMessageCodec { VideoFiltersApiPigeonCodec.shared }
  /// Sets up an instance of `VideoFiltersApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VideoFiltersApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_filters.VideoFiltersApi.loadVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          try api.loadVideo(path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadVideoChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_filters.VideoFiltersApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { _, reply in
        do {
          try api.play()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_filters.VideoFiltersApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let getVideoDurationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_filters.VideoFiltersApi.getVideoDuration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVideoDurationChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVideoDuration()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVideoDurationChannel.setMessageHandler(nil)
    }
    let getVideoPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_filters.VideoFiltersApi.getVideoPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVideoPositionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVideoPosition()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVideoPositionChannel.setMessageHandler(nil)
    }
    let updateFiltersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_filters.VideoFiltersApi.updateFilters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateFiltersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! VideoFilterConfig
        do {
          try api.updateFilters(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateFiltersChannel.setMessageHandler(nil)
    }
    let setLutCubePathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_filters.VideoFiltersApi.setLutCubePath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLutCubePathChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          try api.setLutCubePath(path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLutCubePathChannel.setMessageHandler(nil)
    }
    let setHaldPngPathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_filters.VideoFiltersApi.setHaldPngPath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHaldPngPathChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          try api.setHaldPngPath(path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setHaldPngPathChannel.setMessageHandler(nil)
    }
  }
}
